<?php
return $dice_game =
[ 'type' => 'procedure',
  'descriptions' => [
// 1から6までのランダムな数値を変数[[rand_name]]に代入するサブルーチンを定義
    [ 'type' => 'function',
      'name' => 'function::define',
      'args' => [
        [ 'type' => 'constant',
          'value' => 'u_get_rand'
        ],
        [ 'type' => 'user_function',
          'descriptions' => [
            [ 'type' => 'function',
              'name' => 'db::set',
              'args' => [
                [ 'type' => 'function',
                  'name' => 'db::get',
                  'args' => [
                    [ 'type' => 'constant',
                      'value' => 'rand_name',
                    ],
                  ],
                ],
                [ 'type' => 'function',
                  'name' => 'system::mt_rand',
                  'args' => [
                    [ 'type' => 'constant',
                      'value' => 1
                    ],
                    [ 'type' => 'constant',
                      'value' => 6
                    ],
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
    ],
// 変数[[result_name]]を加算
    [ 'type' => 'function',
      'name' => 'function::define',
      'args' => [
        [ 'type' => 'constant',
          'value' => 'u_add_result'
        ],
        [ 'type' => 'user_function',
          'descriptions' => [
            [ 'type' => 'function',
              'name' => 'db::set',
              'args' => [
                [ 'type' => 'function',
                  'name' => 'db::get',
                  'args' => [
                    [ 'type' => 'constant',
                      'value' => 'result_name',
                    ],
                  ],
                ],
                [ 'type' => 'function',
                  'name' => 'system::calc',
                  'args' => [
                    [ 'type' => 'function',
                      'name' => 'db::get',
                      'args' => [
                        [ 'type' => 'function',
                          'name' => 'db::get',
                          'args' => [
                            [ 'type' => 'constant',
                              'value' => 'result_name',
                            ],
                          ],
                        ],
                      ],
                    ],
                    [ 'type' => 'constant',
                      'value' => '+'
                    ],
                    [ 'type' => 'constant',
                      'value' => '1'
                    ],
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
    ],
// 1ゲーム分のサブルーチン
    [ 'type' => 'function',
      'name' => 'function::define',
      'args' => [
        [ 'type' => 'constant',
          'value' => 'game',
        ],
        [ 'type' => 'user_function',
          'descriptions' => [
            // サイコロを振る (player)
            [ 'type' => 'function',
              'name' => 'db::set',
              'args' => [
                [ 'type' => 'constant',
                  'value' => 'rand_name',
                ],
                [ 'type' => 'constant',
                  'value' => 'player',
                ],
              ],
            ],
            [ 'type' => 'function',
              'name' => 'function::execute',
              'args' => [
                [ 'type' => 'constant',
                  'value' => 'u_get_rand',
                ],
              ],
            ],
            // サイコロを振る (enemy)
            [ 'type' => 'function',
              'name' => 'db::set',
              'args' => [
                [ 'type' => 'constant',
                  'value' => 'rand_name',
                ],
                [ 'type' => 'constant',
                  'value' => 'enemy',
                ],
              ],
            ],
            [ 'type' => 'function',
              'name' => 'function::execute',
              'args' => [
                [ 'type' => 'constant',
                  'value' => 'u_get_rand',
                ],
              ],
            ],
            // 出目を表示
            [ 'type' => 'function',
              'name' => 'modui::StaticUI',
              'args' => [
                [ 'type' => 'constant',
                  'value' => 'あなたの目は',
                ],
                [ 'type' => 'function',
                  'name' => 'db::get',
                  'args' => [
                    [ 'type' => 'constant',
                      'value' => 'player'
                    ],
                  ],
                ],
                [ 'type' => 'constant',
                  'value' => 'です<br/>',
                ],
                [ 'type' => 'constant',
                  'value' => '相手の目は',
                ],
                [ 'type' => 'function',
                  'name' => 'db::get',
                  'args' => [
                    [ 'type' => 'constant',
                      'value' => 'enemy'
                    ],
                  ],
                ],
                [ 'type' => 'constant',
                  'value' => 'です<br/>',
                ],
              ],
            ],
            // 結果
            [ 'type' => 'function',
              'name' => 'system::if',
              'args' => [
                [ 'type' => 'function',
                  'name' => 'system::bool',
                  'args' => [
                    [ 'type' => 'function',
                      'name' => 'db::get',
                      'args' => [
                        [ 'type' => 'constant',
                          'value' => 'player',
                        ],
                      ],
                    ],
                    [ 'type' => 'constant',
                      'value' => '>'
                    ],
                    [ 'type' => 'function',
                      'name' => 'db::get',
                      'args' => [
                        [ 'type' => 'constant',
                          'value' => 'enemy'
                        ],
                      ],
                    ],
                  ],
                ],
                [ 'type' => 'user_function',
                  'descriptions' => [
                    [ 'type' => 'function',
                      'name' => 'modui::StaticUI',
                      'args' => [
                        [ 'type' => 'constant',
                          'value' => 'あなたの勝ち<br/>',
                        ],
                      ],
                    ],
                    [ 'type' => 'function',
                      'name' => 'db::set',
                      'args' => [
                        [ 'type' => 'constant',
                          'value' => 'result_name',
                        ],
                        [ 'type' => 'constant',
                          'value' => 'win',
                        ],
                      ],
                    ],
                  ],
                ],
                [ 'type' => 'user_function',
                  'descriptions' => [
                    [ 'type' => 'function',
                      'name' => 'system::if',
                      'args' => [
                        [ 'type' => 'function',
                          'name' => 'system::bool',
                          'args' => [
                            [ 'type' => 'function',
                              'name' => 'db::get',
                              'args' => [
                                [ 'type' => 'constant',
                                  'value' => 'player',
                                ],
                              ],
                            ],
                            [ 'type' => 'constant',
                              'value' => '<'
                            ],
                            [ 'type' => 'function',
                              'name' => 'db::get',
                              'args' => [
                                [ 'type' => 'constant',
                                  'value' => 'enemy'
                                ],
                              ],
                            ],
                          ],
                        ],
                        [ 'type' => 'user_function',
                          'descriptions' => [
                            [ 'type' => 'function',
                              'name' => 'modui::StaticUI',
                              'args' => [
                                [ 'type' => 'constant',
                                  'value' => '相手の勝ち<br/>',
                                ],
                              ],
                            ],
                            [ 'type' => 'function',
                              'name' => 'db::set',
                              'args' => [
                                [ 'type' => 'constant',
                                  'value' => 'result_name',
                                ],
                                [ 'type' => 'constant',
                                  'value' => 'lose',
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                    ],
                  ],
                ],
              ],
            ],
            // 引分ならもう一回
            [ 'type' => 'function',
              'name' => 'system::if',
              'args' => [
                [ 'type' => 'function',
                  'name' => 'system::bool',
                  'args' => [
                    [ 'type' => 'function',
                      'name' => 'db::get',
                      'args' => [
                        [ 'type' => 'constant',
                          'value' => 'player',
                        ],
                      ],
                    ],
                    [ 'type' => 'constant',
                      'value' => '=='
                    ],
                    [ 'type' => 'function',
                      'name' => 'db::get',
                      'args' => [
                        [ 'type' => 'constant',
                          'value' => 'enemy'
                        ],
                      ],
                    ],
                  ],
                ],
                [ 'type' => 'user_function',
                  'descriptions' => [
                    [ 'type' => 'function',
                      'name' => 'modui::StaticUI',
                      'args' => [
                        [ 'type' => 'constant',
                          'value' => '引分 - やり直し<br/>',
                        ],
                      ],
                    ],
                    [ 'type' => 'function',
                      'name' => 'function::execute',
                      'args' => [
                        [ 'type' => 'constant',
                          'value' => 'game',
                        ],
                      ],
                    ],
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
    ],
// 説明表示
    [ 'type' => 'function',
      'name' => 'modui::StaticUI',
      'args' => [
        [ 'type' => 'constant',
          'value' => 'サイコロ勝負(出目の大きい方が勝ち)<br/>',
        ],
      ],
    ],
// ゲームを数回行う
    [ 'type' => 'function',
      'name' => 'modui::StaticUI',
      'args' => [
        [ 'type' => 'constant',
          'value' => '--------------------<br/>',
        ],
      ],
    ],
    [ 'type' => 'function',
      'name' => 'system::loop',
      'args' => [
        [ 'type' => 'constant',
          'value' => 10,
        ],
        [ 'type' => 'user_function',
          'descriptions' => [
            [ 'type' => 'function',
              'name' => 'function::execute',
              'args' => [
                [ 'type' => 'constant',
                  'value' => 'game',
                ],
              ],
            ],
            [ 'type' => 'function',
              'name' => 'modui::StaticUI',
              'args' => [
                [ 'type' => 'constant',
                  'value' => '--------------------<br/>',
                ],
              ],
            ],
          ],
        ],
      ],
    ],
// 結果処理
    [ 'type' => 'function',
      'name' => 'function::execute',
      'args' => [
        [ 'type' => 'constant',
          'value' => 'u_add_result',
        ],
      ],
    ],
// 勝率計算
    [ 'type' => 'function',
      'name' => 'modui::StaticUI',
      'args' => [
        [ 'type' => 'constant',
          'value' => '勝率 : ',
        ],
        [ 'type' => 'function',
          'name' => 'system::calc',
          'args' => [
            [ 'type' => 'function',
              'name' => 'db::get',
              'args' => [
                [ 'type' => 'constant',
                  'value' => 'win',
                ],
              ],
            ],
            [ 'type' => 'constant',
              'value' => '/',
            ],
            [ 'type' => 'function',
              'name' => 'system::calc',
              'args' => [
                [ 'type' => 'function',
                  'name' => 'db::get',
                  'args' => [
                    [ 'type' => 'constant',
                      'value' => 'win',
                    ],
                  ],
                ],
                [ 'type' => 'constant',
                  'value' => '+',
                ],
                [ 'type' => 'function',
                  'name' => 'db::get',
                  'args' => [
                    [ 'type' => 'constant',
                      'value' => 'lose',
                    ],
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
    ],
// end
  ],
];
